# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='date created',
            new_name='creation_date',
        ),
    ]
