# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20170220_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
