# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_stream_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='cover_art',
            field=models.ImageField(default='settings.MEDIA_ROOT/default_cover.jpg', upload_to='streams/cover_art/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='stream',
            name='thumbnail',
            field=models.ImageField(default='settings.MEDIA_ROOT/default_thumb.jpg', upload_to='streams/thumbnails/%Y/%m/%d'),
        ),
    ]
