# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20170221_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='cover_art',
            field=models.ImageField(default='/Users/andrewfarrar/projects/relayer/streams/static/images/upload/default_cover.jpg', upload_to='streams/cover_art/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='thumbnail',
            field=models.ImageField(default='/Users/andrewfarrar/projects/relayer/streams/static/images/upload/default_thumb.jpg', upload_to='streams/thumbnails/%Y/%m/%d'),
        ),
    ]
