# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_auto_20170221_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='cover_art',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='thumbnail',
        ),
    ]
