# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_auto_20170221_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
