# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import streams.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0008_stream_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='created_by',
        ),
        migrations.AddField(
            model_name='stream',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_key',
            field=models.CharField(default=streams.models.generate_stream_key, max_length=32),
        ),
    ]
